#MAIN#
###
GET http://localhost:3333/api/v1/


#STUDENTS#
###
GET http://localhost:3333/api/v1/students

###
POST http://localhost:3333/api/v1/students
Content-Type: application/json

{
  "name": "Thiago"
}

#CLASSES#
###
GET http://localhost:3333/api/v1/class

###
POST http://localhost:3333/api/v1/class
Content-Type: application/json

{
  "name": "Desenvolvimento de Sistemas"
}

#RANK#
###
GET http://localhost:3333/api/v1/rank

###
POST http://localhost:3333/api/v1/rank
Content-Type: application/json

{
  "student_id": 2,
  "class_id": 1,
  "score": 40
}
